### ISSUE TITLE
runScan doesn't work

### ISSUE THREAD

**Issue by kennydataml** [tayganr/purviewcli#14]
I'm getting an internal server error when I try to runScan.
Not sure if this is a msft problem. 
Do you have any ideas?

I've also tried creating custom code to hit the run scan API as per docs but doesn't work: 
https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/scan-result/run-scan

if I try readScanHistory, this does work.
this also falls under the `scan-result` API in msft docs. the main difference being `GET` vs `PUT`. very puzzled.

**Comment by tayganr** [comment]
Thanks  @kennydataml , this should now be fixed in 0.1.34. The [scanningdataplane ](https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/scan-result/run-scan) documentation appears to be out of sync with what is actually occuring. Monitoring Purview Studio, the HTTP method appears to have changed from **PUT** to **POST**, the **runId** parameter also appears to no longer be required. Example: `pv scan runScan --dataSourceName "AzureDataLakeStorage" --scanName "Scan-O2F"`
